### ISSUE TITLE
tile cannot extend outside image

### ISSUE THREAD

**Issue by miguelshta21** [leoee/Tibia-Bot-12-#1]
File "C:\Python37\lib\site-packages\PIL\ImageFile.py", line 504, in _save
    e.setimage(im.im, b)
SystemError: tile cannot extend outside image

**Comment by leoee** [comment]
Did you get this error when starting the script?

**Comment by miguelshta21** [comment]
when try to configure screen

**Comment by leoee** [comment]
You need to cut the image from low points to high points (first left points and after that, right points). You may be cutting the first point as the higher point and this will cause the error that you sent.

How to do that? Start selecting the point more left side and then the right side points.

Thank you very much to notice the error. I will fix that as soon as possible. Untill that, try what i said.

**Comment by miguelshta21** [comment]
did u have discord? maybe because im running it on linux

**Comment by leoee** [comment]
Yeah! What is your user? I can ping you there.

**Comment by miguelshta21** [comment]
Riven Lara#2774
