### ISSUE TITLE
Muito Bom...

### ISSUE THREAD

**Issue by MuriloChianfa** [leoee/Tibia-Bot-12-#2]
Opa, fala ai amigo, gostei bastante do projeto kkkk, eu também estava desenvolvendo um bot, mas o meu foco era no global sabe, ele até que funciona bem, mas sobre a parte de auto attack no cavebot eu me perdi um pouco, e todas as ideias que eu já tentei, não deram 100% certo kkkkkkkkkk.

Se você me permitir, gostaria de estudar seu código, pra ver como que você faz o auto attack, qualquer coisa se precisar também posso dar uma ajuda aqui no projeto... Vlw abraços.

**Comment by leoee** [comment]
Oi Murilo, ando meio sem tempo para adicionar novas features. Me passa seu Discord e podemos trocar umas ideias. O meu auto attack não está 100% funcional.

**Comment by MuriloChianfa** [comment]
Beleza, meu id: Light#1555 dai depois conversamos então.
