### ISSUE TITLE
NameError: name 'ttk' is not defined

### ISSUE THREAD

**Issue by rbcorrea** [leoee/Tibia-Bot-12-#4]
Opa, falaí, primeiramente parabéns pelo projeto!

Cara, fiz o recomendado e estou com esse erro aqui:

**NameError: name 'ttk' is not defined**

Procurei pra adicionar no discord.

**Comment by leoee** [comment]
Oi Rodrigo,

Qual a versão do seu Python?

**Comment by leoee** [comment]
Fechando essa issue uma vez que foi resolvido na outra.
