### ISSUE TITLE
NameError: name 'ttk' is not defined

### ISSUE THREAD

**Issue by rbcorrea** [leoee/Tibia-Bot-12-#5]
Opa, falaí, primeiramente parabéns pelo projeto!

Cara, fiz o recomendado e estou com esse erro aqui:

**NameError: name 'ttk' is not defined**

Procurei pra adicionar no discord. 
Sou o hrodricx#0206

Se eu puder ajudar em algo, só me dar um toque.

**Comment by rbcorrea** [comment]
Cara, acabei de ver aqui que somente importando diretamente o ttk ele funcionou bem.

from tkinter import ttk

**Comment by leoee** [comment]
Oi Rodrigo,

Pode ser que seja algo na sua versão do Python. Eu costumo utilizar a 3.7.2.
Qual versão você estava utilizando?

Que bom que deu certo :)
Você pode me adicionar no Discord: Leo#8924

**Comment by rbcorrea** [comment]
A minha é 3.9.5

Valeu!

**Comment by leoee** [comment]
Vou adicionar uma nota para caso alguém utilize as mais recentes.

Obrigado por informar.
